export const industryOptions: string[] = [
    "Accounting",
    "Advertising",
    "Agriculture",
    "Automotive",
    "Banking",
    "Beauty",
    "Construction",
    "Consulting",
    "Education",
    "Energy",
    "Entertainment",
    "Fashion",
    "Finance",
    "Food and Beverage",
    "Healthcare",
    "Hospitality",
    "Information Technology",
    "Insurance",
    "Manufacturing",
    "Media",
    "Nonprofit",
    "Real Estate",
    "Retail",
    "Telecommunications",
    "Transportation",
    "Travel",
    "Other"
  ];